### ISSUE TITLE
False positives checking the system with valid credentials if user is not in RDP Users list.

### ISSUE THREAD

**Issue by nikallass** [nccgroup/BKScan#2]
### Steps to reproduce:

0) Create user `test` with password `123`.

1) Add user `test` to Remote Desktop User list:
![image](https://user-images.githubusercontent.com/10115306/59515200-3cba7700-8ec7-11e9-910c-6a7bca280da0.png)

3) Run BKscan `./bkscan.sh -t 10.0.2.15 -u test -p 123 --debug`. Bunch of MST120 was sended and we get **true positive**:
![image](https://user-images.githubusercontent.com/10115306/59515326-899e4d80-8ec7-11e9-9eb1-43c524b95322.png)

4) Remove user `test` from Remote Desktop User list:
![image](https://user-images.githubusercontent.com/10115306/59515391-b05c8400-8ec7-11e9-82e2-3fe861aa56cd.png)

5) Run BKscan `./bkscan.sh -t 10.0.2.15 -u test -p 123 --debug`. NLA passes but we get false positive because RDP is restricted for this user and MST120 packets are not sended:
![image](https://user-images.githubusercontent.com/10115306/59515543-092c1c80-8ec8-11e9-9b43-6a624efe339b.png)

**Notice: Server said: `ERRINFO_SERVER_INSUFFICIENT_PRIVILEGES (0x00000009):The user cannot connect to the server due to insufficient access privileges.` but BKscan wrote: `[!] Target is VULNERABLE!!!`**

**Comment by nikallass** [comment]
I fixed it in https://github.com/nccgroup/BKScan/pull/1/commits/cc2b9983e07796ad7ba9311a19b6ceda192cd633

![image](https://user-images.githubusercontent.com/10115306/59523899-29b1a200-8edb-11e9-8a8f-6fe164e695df.png)

**Comment by saidelike** [comment]
Thanks nikallass for your issue request. I also fixed it in parallel in 55bbb552a571ae287350d5d2e2deefe5f8bae5a7. If it happens to not work, let me know.
