### ISSUE TITLE
failed to open display

### ISSUE THREAD

**Issue by seajaysec** [nccgroup/BKScan#3]
Hey, just re-installed the docker image and am still getting this error when I try to use bkscan.

```
./bkscan.sh -t █.█.█.█ -u █████ -p █████ --debug
[+] Targeting █.█.█.█:3389...
[+] Using provided credentials, will support NLA
No protocol specified
[22:47:17:428] [1:1] [ERROR][com.freerdp.client.x11] - failed to open display: :1
[22:47:17:428] [1:1] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.
```

**Comment by seajaysec** [comment]
After posting this I saw the PR for a fix to this problem. Loaded that build on my side and it worked without a hitch.

https://github.com/nccgroup/BKScan/pull/1

**Comment by saidelike** [comment]
Thanks for confirming. Closing then.
